name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      #- name: Cache Pub packages
      #  uses: actions/cache@v4
      #  with:
      #    path: ~/.pub-cache
      #    key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
      #    restore-keys: |
      #      ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
